"use client";

import { useState, useEffect, useRef } from "react";
import { FREQUENCY_OPTIONS, type InventoryItem } from "@/lib/inventory-data";
import { type HomeAsset } from "@/lib/home-assets-data";
import { computeNextReminderDate } from "@/lib/date-utils";
import { XIcon, ChevronDownIcon } from "@/components/icons";
import DatePicker from "@/components/ui/DatePicker";
import CurrencyInput from "@/components/ui/CurrencyInput";

interface AddInventoryItemModalProps {
  item?: InventoryItem;
  homeAssets?: HomeAsset[];
  onSave: (data: Omit<InventoryItem, "id" | "createdAt">) => void;
  onClose: () => void;
}

function todayString(): string {
  return new Date().toISOString().split("T")[0];
}

export default function AddInventoryItemModal({
  item,
  homeAssets = [],
  onSave,
  onClose,
}: AddInventoryItemModalProps) {
  const isEditing = !!item;
  const isAutoGenerated = !!item?.homeAssetId;
  const [name, setName] = useState(item?.name ?? "");
  const [description, setDescription] = useState(item?.description ?? "");
  const [frequencyMonths, setFrequencyMonths] = useState(
    item?.frequencyMonths ?? 6
  );
  const [lastOrderedDate, setLastOrderedDate] = useState(
    item?.lastOrderedDate ?? ""
  );
  const [purchaseUrl, setPurchaseUrl] = useState(item?.purchaseUrl ?? "");
  const [thumbnailUrl, setThumbnailUrl] = useState(item?.thumbnailUrl ?? "");
  const [notes, setNotes] = useState(item?.notes ?? "");
  const [cost, setCost] = useState(item?.cost != null ? String(item.cost) : "");
  const [homeAssetId, setHomeAssetId] = useState(item?.homeAssetId ?? "");
  const nameRef = useRef<HTMLInputElement>(null);
  const isValid = name.trim() !== "";

  useEffect(() => {
    nameRef.current?.focus();
  }, []);

  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [onClose]);

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!isValid) return;

    // For auto-generated items, preserve existing values for hidden fields
    const effectiveFrequency = isAutoGenerated ? (item?.frequencyMonths ?? frequencyMonths) : frequencyMonths;
    const effectiveLastOrdered = isAutoGenerated ? (item?.lastOrderedDate ?? null) : (lastOrderedDate || null);
    const effectivePurchaseUrl = isAutoGenerated ? (item?.purchaseUrl ?? "") : purchaseUrl.trim();
    const effectiveThumbnailUrl = isAutoGenerated ? (item?.thumbnailUrl ?? "") : thumbnailUrl.trim();
    const effectiveNotes = isAutoGenerated ? (item?.notes ?? "") : notes.trim();
    const effectiveCost = isAutoGenerated ? (item?.cost ?? null) : (cost.trim() ? parseFloat(cost) : null);

    const baseDate = effectiveLastOrdered || todayString();
    const nextReminderDate = computeNextReminderDate(baseDate, effectiveFrequency);

    onSave({
      name: name.trim(),
      description: description.trim(),
      frequencyMonths: effectiveFrequency,
      lastOrderedDate: effectiveLastOrdered,
      nextReminderDate,
      purchaseUrl: effectivePurchaseUrl,
      thumbnailUrl: effectiveThumbnailUrl,
      notes: effectiveNotes,
      cost: effectiveCost,
      homeAssetId: homeAssetId || null,
    });
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-[2px]"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="bg-surface rounded-[var(--radius-lg)] border border-border shadow-[var(--shadow-hover)] w-full max-w-lg mx-4 max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-border">
          <h2 className="text-[15px] font-semibold text-text-primary">
            {isEditing ? "Edit Item" : "Add Inventory Item"}
          </h2>
          <button
            onClick={onClose}
            className="flex items-center justify-center rounded-[var(--radius-sm)] p-1.5 text-text-3 hover:bg-border hover:text-text-primary transition-all duration-[120ms]"
            aria-label="Close modal"
          >
            <XIcon width={16} height={16} />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-5 flex flex-col gap-4">
          {/* Name */}
          <label className="flex flex-col gap-1.5">
            <span className="text-[13px] font-medium text-text-primary">
              Item Name <span className="text-red">*</span>
            </span>
            <input
              ref={nameRef}
              type="text"
              required
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="px-3 py-[7px] text-[13px] bg-surface border border-border rounded-[var(--radius-sm)] text-text-primary placeholder:text-text-4 focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent/30 transition-all duration-[120ms]"
              placeholder="e.g. AC Filter (20x25x1)"
            />
          </label>

          {/* Description */}
          <label className="flex flex-col gap-1.5">
            <span className="text-[13px] font-medium text-text-primary">
              Description
            </span>
            <input
              type="text"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="px-3 py-[7px] text-[13px] bg-surface border border-border rounded-[var(--radius-sm)] text-text-primary placeholder:text-text-4 focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent/30 transition-all duration-[120ms]"
              placeholder="What this item is for"
            />
          </label>

          {/* Home Asset — hidden for auto-generated items (asset is locked) */}
          {!isAutoGenerated && homeAssets.length > 0 && (
            <label className="flex flex-col gap-1.5">
              <span className="text-[13px] font-medium text-text-primary">
                Home Asset
              </span>
              <div className="relative">
                <select
                  value={homeAssetId}
                  onChange={(e) => setHomeAssetId(e.target.value)}
                  className="w-full appearance-none px-3 py-[7px] pr-8 text-[13px] bg-surface border border-border rounded-[var(--radius-sm)] text-text-primary cursor-pointer focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent/30 transition-all duration-[120ms]"
                >
                  <option value="">None</option>
                  {[...homeAssets]
                    .sort((a, b) => a.name.localeCompare(b.name))
                    .map((a) => (
                    <option key={a.id} value={a.id}>
                      {a.name}
                    </option>
                  ))}
                </select>
                <ChevronDownIcon className="absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none text-text-3" />
              </div>
            </label>
          )}

          {/* Fields below are hidden for auto-generated items */}
          {!isAutoGenerated && (
            <>
              {/* Frequency & Last Ordered */}
              <div className="flex gap-3">
                <label className="flex flex-col gap-1.5 flex-1">
                  <span className="text-[13px] font-medium text-text-primary">
                    Replace Frequency <span className="text-red">*</span>
                  </span>
                  <select
                    value={frequencyMonths}
                    onChange={(e) => setFrequencyMonths(Number(e.target.value))}
                    className="px-3 py-[7px] text-[13px] bg-surface border border-border rounded-[var(--radius-sm)] text-text-primary focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent/30 transition-all duration-[120ms]"
                  >
                    {FREQUENCY_OPTIONS.map((opt) => (
                      <option key={opt.value} value={opt.value}>
                        {opt.label}
                      </option>
                    ))}
                  </select>
                </label>
                <label className="flex flex-col gap-1.5 flex-1">
                  <span className="text-[13px] font-medium text-text-primary">
                    Last Ordered
                  </span>
                  <DatePicker
                    value={lastOrderedDate}
                    onChange={setLastOrderedDate}
                  />
                </label>
              </div>

              {/* Cost */}
              <label className="flex flex-col gap-1.5">
                <span className="text-[13px] font-medium text-text-primary">
                  Cost
                </span>
                <CurrencyInput
                  value={cost}
                  onChange={setCost}
                />
              </label>

              {/* Purchase URL */}
              <label className="flex flex-col gap-1.5">
                <span className="text-[13px] font-medium text-text-primary">
                  Purchase URL
                </span>
                <input
                  type="url"
                  value={purchaseUrl}
                  onChange={(e) => setPurchaseUrl(e.target.value)}
                  className="px-3 py-[7px] text-[13px] bg-surface border border-border rounded-[var(--radius-sm)] text-text-primary placeholder:text-text-4 focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent/30 transition-all duration-[120ms]"
                  placeholder="https://www.amazon.com/..."
                />
              </label>

              {/* Thumbnail URL */}
              <label className="flex flex-col gap-1.5">
                <span className="text-[13px] font-medium text-text-primary">
                  Image URL
                </span>
                <input
                  type="url"
                  value={thumbnailUrl}
                  onChange={(e) => setThumbnailUrl(e.target.value)}
                  className="px-3 py-[7px] text-[13px] bg-surface border border-border rounded-[var(--radius-sm)] text-text-primary placeholder:text-text-4 focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent/30 transition-all duration-[120ms]"
                  placeholder="Right-click product image → Copy image address"
                />
              </label>

              {/* Notes */}
              <label className="flex flex-col gap-1.5">
                <span className="text-[13px] font-medium text-text-primary">
                  Notes
                </span>
                <textarea
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  rows={3}
                  className="px-3 py-[7px] text-[13px] bg-surface border border-border rounded-[var(--radius-sm)] text-text-primary placeholder:text-text-4 resize-none focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent/30 transition-all duration-[120ms]"
                  placeholder="Where to buy, brand preferences, size details..."
                />
              </label>
            </>
          )}

          {/* Actions */}
          <div className="flex justify-end gap-3 pt-2 border-t border-border">
            <button
              type="button"
              onClick={onClose}
              className="inline-flex items-center gap-1.5 px-3.5 py-[7px] rounded-[var(--radius-sm)] border border-border-strong bg-surface text-text-2 text-[13px] font-medium hover:bg-border hover:text-text-primary transition-all duration-[120ms]"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={!isValid}
              className="inline-flex items-center gap-1.5 px-3.5 py-[7px] rounded-[var(--radius-sm)] bg-accent text-white text-[13px] font-medium hover:brightness-110 transition-all duration-[120ms] disabled:opacity-40 disabled:cursor-not-allowed"
            >
              {isEditing ? "Save Changes" : "Add Item"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
